# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appvendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(default='UND', max_length=5, verbose_name='Sigla'),
            preserve_default=False,
        ),
    ]
